Fix NoClassDefFoundError: Remove autoSizeColumn (requires AWT)
Fixed crash caused by autoSizeColumn() trying to use java.awt.font.FontRenderContext
which is not available on Android (AWT is Desktop-Java only).

Solution:
- Removed autoSizeColumn() calls completely
- Set fixed column widths manually using setColumnWidth()
- Column widths: Wochentag=12, Soll/Von/Bis/Pause/Ist=8, Typ=10

Column width is specified in 1/256th of a character width, hence * 256.

Error was:
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/font/FontRenderContext;
at org.apache.poi.ss.util.SheetUtil.<clinit>(SheetUtil.java:98)
at org.apache.poi.xssf.usermodel.XSSFSheet.autoSizeColumn(XSSFSheet.java:497)